# -*- coding: utf-8 -*-
"""Project Clustering Blobs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/thecodescholar/Python_ML_June_21/blob/main/Project%20Clustering%20Blobs.ipynb

# Unsupervised Machine Learning - KMeans

Support vector machines (SVMs) are a set of supervised learning methods used for classification, regression and outliers detection. SVMs are one of the most robust prediction methods. 

Sources: 
[sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html?highlight=kmeans#sklearn.cluster.KMeans), [wikipedia](https://en.wikipedia.org/wiki/K-means_clustering)

![kmeans.png](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/52579/versions/9/screenshot.jpg)
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

# Take make moons in built dataset

data_ = datasets.make_crescents(200)

# check the dataset

data_

# create input dataframe

inputData = pd.DataFrame(data=data_[0])

inputData.head()

# create output dataframe

outputData = pd.DataFrame(data=data_[0])
outputData.head()

# create a scatter plot for inputData set

plt.scatter(inputData[0],inputdata[1])

# create a scatter plot for inputData set with outputData color

plt.scatter(inputData[0],inputdata[1],c=outData)



# Call the sklearn Kmeans and make a model with 200 samples

from sklearn.cluster import KMeans
model=KMeans(n_clusters=5)
model.fit(inputData)
model_fit

#model_fit

# check for labels
model.labels_



# call metrics and check silhoutte score
from sklearn import metrics
metrics.silhouette_score(inputData,model.labels)

# create a scatter plot for inputData set with model labels color
plt.scatter(inputdata[0],inputdata[1],c=model.labels)

"""#### finding right number of cluster"""

cluster_range = range(1, 20)
error_list = []

for i in cluster_range:
    model = KMeans(n_clusters=i)
    model.fit(inputData)
    res = model.inertia_
    error_list.append(res)

import matplotlib.pyplot as plt

plt.plot(cluster_range, error_list, marker = "o", color = "g", markersize = 10)
plt.xlabel("Cluster Range")
plt.ylabel("IntraCluster Sum")
plt.title("KMeans")
plt.show()



